### PR TITLE
F-Droid

### PR DESCRIPTION
**Pull request by dimqua**
Please consider to add the app to F-Droid. 

In order to do this the following changes are requeried:
https://gitlab.com/fdroid/rfp/issues/333#note_40552283

### CODE REVIEW

**Comment by NHellFire** [comment]
Thanks, I'll check this next week when I'm home and see if there's any other changes to do.

**Comment by NHellFire** [comment]
Merged. Took longer than I'd hoped to find time to check it.

**Comment by dimqua** [comment]
@NHellFire can you please release a new version? Which is 0.9.73.1 currently.

**Comment by NHellFire** [comment]
Done now. I forgot to push the tags

**Pull request merged**
